# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboardView', models.BooleanField()),
                ('mapView', models.BooleanField()),
                ('distanceView', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('beginDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('totalTime', models.IntegerField()),
                ('distanceTraveled', models.IntegerField()),
                ('averageSpeed', models.IntegerField()),
                ('topSpeed', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='selectmode',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeProject.Session'),
        ),
    ]
